# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:  # Manually triggered workflow

permissions:
  contents: write # We generate static HTML, JS, CSS so we need write access to the repo
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean test

    - name: Publish TestNG Report 
      uses: mikepenz/action-junit-report@v2 
      if: always()
      with:
        path: '**/target/surefire-reports/testng-results.xml' 
        report_name: UI TestNG Report 

    - name: Upload Extent Report 
      uses: actions/upload-artifact@v2 
      with:
        name: extent-report
        path: target/extentReport/Spark.html

    - name: Publish Extent Report to gh-pages
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout -b gh-pages
        mv target/extentReport/Spark.html .
        git add ./Spark.html
        git commit -m "Update Extent Report"
        git push --set-upstream origin gh-pages
      env:
       GH_TOKEN: ${{ secrets.MYTOKEN }}
       GIT_COMMITTER_NAME: github-actions
       GIT_COMMITTER_EMAIL: github-actions@github.com
